server:
  port: 8079
spring:
  datasource:
    url: jdbc:mysql://123.57.87.54:3306/ssm2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: bms
    password: bms@2018
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.zimug.bootlaunch: debug